//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanHo()
        {
            this.CanHo_CuDan = new HashSet<CanHo_CuDan>();
            this.CanHo_VatTu = new HashSet<CanHo_VatTu>();
            this.CuDans = new HashSet<CuDan>();
            this.HoaDonCuDans = new HashSet<HoaDonCuDan>();
        }
    
        public int CanHoID { get; set; }
        public string SoCanHo { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public int TangID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanHo_CuDan> CanHo_CuDan { get; set; }
        public virtual Tang Tang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanHo_VatTu> CanHo_VatTu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuDan> CuDans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonCuDan> HoaDonCuDans { get; set; }
    }
}
