//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonTM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonTM()
        {
            this.HoaDonTM_ChiTiet = new HashSet<HoaDonTM_ChiTiet>();
        }
    
        public int HoaDonTMID { get; set; }
        public int MatBangID { get; set; }
        public string NoiDung { get; set; }
        public decimal SoTien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonTM_ChiTiet> HoaDonTM_ChiTiet { get; set; }
        public virtual MatBangThuongMai MatBangThuongMai { get; set; }
    }
}
