//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRun
    {
        public int JobID { get; set; }
        public string JobType { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string ParamsJson { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public string Status { get; set; }
        public string Error { get; set; }
    
        public virtual ModelRegistry ModelRegistry { get; set; }
    }
}
