//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelRegistry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelRegistry()
        {
            this.InventoryForecasts = new HashSet<InventoryForecast>();
            this.JobRuns = new HashSet<JobRun>();
        }
    
        public int ModelID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Task { get; set; }
        public string Framework { get; set; }
        public string Uri { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryForecast> InventoryForecasts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRun> JobRuns { get; set; }
    }
}
