//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OAuthAccount()
        {
            this.OAuthTokens = new HashSet<OAuthToken>();
        }
    
        public int OAuthAccountID { get; set; }
        public int TaiKhoanID { get; set; }
        public int ProviderID { get; set; }
        public string ProviderUserId { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public System.DateTime LinkedAt { get; set; }
    
        public virtual OAuthProvider OAuthProvider { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OAuthToken> OAuthTokens { get; set; }
    }
}
