//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthToken
    {
        public int TokenID { get; set; }
        public int OAuthAccountID { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public string Scope { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual OAuthAccount OAuthAccount { get; set; }
    }
}
