//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanHo_VatTu
    {
        public int Id { get; set; }
        public int CanHoID { get; set; }
        public int VatTuID { get; set; }
        public int SoLuong { get; set; }
    
        public virtual CanHo CanHo { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
