//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonCuDan
    {
        public int HoaDonID { get; set; }
        public int CuDanID { get; set; }
        public int CanHoID { get; set; }
        public string LoaiDichVu { get; set; }
        public decimal SoTien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual CanHo CanHo { get; set; }
        public virtual CuDan CuDan { get; set; }
    }
}
