//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAudit
    {
        public int Id { get; set; }
        public int VatTuID { get; set; }
        public System.DateTime SnapshotAt { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Note { get; set; }
    
        public virtual VatTu VatTu { get; set; }
    }
}
