//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryForecast
    {
        public int Id { get; set; }
        public int VatTuID { get; set; }
        public System.DateTime ForecastDate { get; set; }
        public decimal ForecastQty { get; set; }
        public Nullable<decimal> Lower95 { get; set; }
        public Nullable<decimal> Upper95 { get; set; }
        public Nullable<int> ModelID { get; set; }
    
        public virtual ModelRegistry ModelRegistry { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
