//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAudit
    {
        public int AuditID { get; set; }
        public Nullable<int> TaiKhoanID { get; set; }
        public string Username { get; set; }
        public string ProviderName { get; set; }
        public bool Success { get; set; }
        public string ClientIP { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime LoggedAt { get; set; }
        public string Message { get; set; }
    }
}
