//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatBangThuongMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatBangThuongMai()
        {
            this.HoaDonTMs = new HashSet<HoaDonTM>();
            this.MatBang_VatTu = new HashSet<MatBang_VatTu>();
        }
    
        public int MatBangID { get; set; }
        public string TenMatBang { get; set; }
        public Nullable<decimal> DienTich { get; set; }
        public Nullable<decimal> GiaThue { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonTM> HoaDonTMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatBang_VatTu> MatBang_VatTu { get; set; }
    }
}
