//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanlychungcuEntities : DbContext
    {
        public QuanlychungcuEntities()
            : base("name=QuanlychungcuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostSery> CostSeries { get; set; }
        public virtual DbSet<InventoryAudit> InventoryAudits { get; set; }
        public virtual DbSet<InventoryForecast> InventoryForecasts { get; set; }
        public virtual DbSet<JobRun> JobRuns { get; set; }
        public virtual DbSet<ModelRegistry> ModelRegistries { get; set; }
        public virtual DbSet<SearchIndex> SearchIndexes { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CanHo> CanHoes { get; set; }
        public virtual DbSet<CanHo_CuDan> CanHo_CuDan { get; set; }
        public virtual DbSet<CanHo_VatTu> CanHo_VatTu { get; set; }
        public virtual DbSet<CuDan> CuDans { get; set; }
        public virtual DbSet<HoaDonCuDan> HoaDonCuDans { get; set; }
        public virtual DbSet<HoaDonTM> HoaDonTMs { get; set; }
        public virtual DbSet<HoaDonTM_ChiTiet> HoaDonTM_ChiTiet { get; set; }
        public virtual DbSet<LoginAudit> LoginAudits { get; set; }
        public virtual DbSet<MatBang_VatTu> MatBang_VatTu { get; set; }
        public virtual DbSet<MatBangThuongMai> MatBangThuongMais { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<OAuthAccount> OAuthAccounts { get; set; }
        public virtual DbSet<OAuthProvider> OAuthProviders { get; set; }
        public virtual DbSet<OAuthToken> OAuthTokens { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Tang> Tangs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
        public virtual DbSet<VatTu> VatTus { get; set; }
        public virtual DbSet<XeDap> XeDaps { get; set; }
        public virtual DbSet<XeMay> XeMays { get; set; }
        public virtual DbSet<XeOTo> XeOToes { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
    }
}
