//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeMay
    {
        public int XeMayID { get; set; }
        public int CuDanID { get; set; }
        public string BKS { get; set; }
    
        public virtual CuDan CuDan { get; set; }
    }
}
